server.port=9100

spring.application.name=like-service
spring.datasource.url=jdbc:postgresql://localhost:5432/social_service_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG


