server:
  port: 9100

spring:
  application:
    name: like-service

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"

  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

services:
  auth:
    base-url: http://localhost:9000
  profile:
    base-url: http://localhost:9001
  post:
    base-url: http://localhost:9002

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    feign: DEBUG


